### ISSUE TITLE
Override the "forgot password" functionality?

### ISSUE THREAD

**Issue by pR0Ps** [jellyfin/jellyfin-plugin-ldapauth#22]
New to Jellyfin plugins. Is is possible for plugins to override the default "forgot password" functionality?

Since users from LDAP aren't managed by Jellyfin, having the "forgot password" button go through the normal flow isn't useful. It would be better if there was some way to hook into it, detect that the username entered is LDAP-managed, and redirect the user to a URL where they can reset their LDAP password instead.

Feel free to close this if it's not possible.

**Comment by dkanada** [comment]
What interface would exist at the specified address? Just curious, I was considering some other solutions for this issue.

**Comment by pR0Ps** [comment]
@dkanada: I would imagine an interface that takes an email/username and handles a password reset. Maybe something like https://github.com/ltb-project/self-service-password

**Comment by crobibero** [comment]
We don't plan on implementing password change from the LDAP plugin as we believe it should be read-only.

**Comment by pR0Ps** [comment]
I'm not saying that Jellyfin should change the LDAP password at all. In fact, I agree with you.

The issue is that right now, if the LDAP plugin is enabled and a user clicks "reset password", they get sent through the normal password reset process without any indication that it's not going to work. This is super frustrating.

The issue is asking for a way to display a "Sorry, Jellyfin can't reset your password. Go to <some URL> to manage your account" message instead of pretending to reset their password and not actually doing it.

Can this issue be reopened?

**Comment by masonh** [comment]
This is relevant for both the forgot password function and the password change in the user's profile page.

**Comment by crobibero** [comment]
Please see https://github.com/jellyfin/jellyfin-plugin-ldapauth/pull/106

**Comment by bilde2910** [comment]
While this is an old and long closed issue, I figured out another way to accomplish this and decided to post it here because this issue is still relevant, appears high up in search results when you try to look for a solution, and I don't want to be [this guy](https://xkcd.com/979/).

This can be accomplished using the branding features in Jellyfin. By simply removing the button using custom CSS and adding a new link using the "disclaimer" custom HTML, you can direct people away from the native reset flow and onto your own self-service credentials reset page in e.g. Keycloak or whichever SSO solution you are using. It might not be the cleanest solution, but it's a much better end user experience than the message box approach shown in #106.

In the Admin Dashboard » Settings » General » Branding, add the following (substitute the URL and text to your liking):

- Login disclaimer:
  ```
  <a href="https://link.to/your/password-reset-page.html" target="_blank">Forgot password?</a>
  ```
- Custom CSS code:
  ```
  button.btnForgotPassword { display: none !important; }
  ```

For example, this:

![ksnip_20240915-154306](https://github.com/user-attachments/assets/fe2c1374-2824-4050-bb94-ff31d9747fde)

Results in this on the login page:

![ksnip_20240915-154607](https://github.com/user-attachments/assets/b7ddc5e4-b1cd-418d-95d4-3a32d262e012)

I'm not sure if it was intentional that HTML could be displayed on the login page like this rather than just plain text, but it apparently can be, allowing it to be used for this purpose.
